source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SwiftLinkPreviewExample' do
  	use_frameworks!
  	pod 'SwiftLinkPreview', :path => '../'
  
  	pod 'SwiftyDrop', '~>2.0'
	pod 'ImageSlideshow', '~> 0.3'
	pod 'ImageSlideshow/Alamofire'
end
