# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SwiftLinkPreviewExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftLinkPreviewExample
  pod 'Alamofire', '5.4.1'
  pod 'SwiftyDrop', '4.2.0'
  pod 'ImageSlideshow', '1.9.1'
  pod 'ImageSlideshow/Alamofire', '1.9.1'
  pod 'SwiftLinkPreview', :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if ['SwiftyDrop'].include?(target.name)
          config.build_settings['SWIFT_VERSION'] = '4.2'
      else
          config.build_settings['SWIFT_VERSION'] = '5.0'
      end
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end